# fly.toml app configuration file generated for warehouse-database on 2025-02-26T12:06:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'warehouse-database'
primary_region = 'otp'

[build]

[services]
  protocol = "tcp"
  internal_port = 5432
  external_ports = [5432]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
